### ISSUE TITLE
Questions about training code

### ISSUE THREAD

**Issue by Wuziyi616** [RyanHangZhou/DUP-Net#1]
Hi! Thank you for sharing this great work! However, I wonder does this repo contains training code for PU-Net? I'm interested in the training process of DUP-Net.
For example, do you use those generated adversarial data to train the PU-Net, or you just use samples that are not attacked to train the PU-Net? Also, when training the PU-Net, is PointNet also being optimized using the reconstructed point cloud after PU-Net?
Hope you can answer my question soon. Thanks!

**Comment by RyanHangZhou** [comment]
We have utilized PU-Net (https://github.com/yulequan/PU-Net) as our _base_ transformer. Yes we use adversarial samples to train PU-Net. When training PU-Net, PointNet is not optimized.

**Comment by Wuziyi616** [comment]
Thank you for your quick response! So let me make sure that, _"When training PU-Net, PointNet is not optimized"_ means the PointNet won't see any adversarial samples (whether before or after passing through PU-Net) in its optimization? And the adversarial samples is used only to train the PU-Net? Looking forward to your reply!
